# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  config.vm.box_check_update = false
  config.ssh.insert_key = false

  config.vm.box = "ubuntu/jammy64"
  config.vm.hostname = "homestead"

  config.vm.network "private_network", ip: "192.168.56.10"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.name = "homestead"
    vb.memory = "4096"
    vb.cpus = "2"
  end

  config.vm.provision :shell, path: '../scripts/setup_ssh_key.sh', run: 'once'

end
